"""remove clinica anexa

Revision ID: c3e341d50b80
Revises: 
Create Date: 2025-06-16 17:19:50.540215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3e341d50b80'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registros_consumo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('turno', sa.String(length=12), nullable=False),
    sa.Column('numero_medidor', sa.String(length=20), nullable=True),
    sa.Column('multiplicador', sa.Integer(), nullable=True),
    sa.Column('hora_captura', sa.Time(), nullable=True),
    sa.Column('rt', sa.Float(), nullable=True),
    sa.Column('a_kwh_d', sa.Float(), nullable=True),
    sa.Column('a_max_kw_d', sa.Float(), nullable=True),
    sa.Column('time_a', sa.Float(), nullable=True),
    sa.Column('b_kwh_d', sa.Float(), nullable=True),
    sa.Column('b_max_kw_d', sa.Float(), nullable=True),
    sa.Column('time_b', sa.Float(), nullable=True),
    sa.Column('c_kwh_d', sa.Float(), nullable=True),
    sa.Column('c_max_kw_d', sa.Float(), nullable=True),
    sa.Column('time_c', sa.Float(), nullable=True),
    sa.Column('kwh_total', sa.Float(), nullable=True),
    sa.Column('kvarh_d', sa.Float(), nullable=True),
    sa.Column('factor_potencia', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registros_consumo')
    # ### end Alembic commands ###
